sudo: false
language: rust

# https://github.com/rust-analyzer/rust-analyzer/blob/7e0a84c36f57def4ef2096f450160dff9f1d74e8/.travis.yml
matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --write-mode=diff
        - cargo test
    - rust: nightly
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy

branches:
  only:
    - main
